# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: "🏗️ Build| WrkstrmMain"

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/wrkstrm-main-build.yml'
      - 'apple/WrkstrmMain/**'
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: apple/WrkstrmMain

jobs:
  xcode-build-matrix:
    name: XcodeBuild Matrix
    strategy:
      matrix:
        os: [self-hosted]
        platform: [iOS, macOS, tvOS, watchOS]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        clean: false
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    - name: Build
      run: xcodebuild build -scheme WrkstrmMain -destination generic/platform=${{ matrix.platform }} CODE_SIGN_IDENTITY=- AD_HOC_CODE_SIGNING_ALLOWED=YES
