name: "\U0001F6A7 Swift Test| WrkstrmMainTests"
on:
  push:
    branches:
    - main
    paths:
    - apple/WrkstrmMain/**
    - .github/workflows/wrkstrm-main-tests-swift.yml
  pull_request:
    branches:
    - main
defaults:
  run:
    working-directory: apple/WrkstrmMain
jobs:
  swift-test:
    strategy:
      matrix:
        os:
        - self-hosted
        - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Cache Swift PM dependencies
      id: cache-spm
      uses: actions/cache@v2
      with:
        path: apple/WrkstrmMain/.build
        key: ${{ runner.os }}-spm-WrkstrmMain-${{ hashFiles('**/Package.resolved')
          }}
        restore-keys: ${{ runner.os }}-spm-WrkstrmMain-
    - name: Check cache
      run: 'echo ''Cache hit: ${{ steps.cache-spm.outputs.cache-hit }}'''
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      if: matrix.os == 'macos-latest' || matrix.os == 'self-hosted'
      with:
        xcode-version: '15.0'
    - name: Swift Describe
      if: steps.cache-spm.outputs.cache-hit != 'true'
      run: swift package describe --type json
    - name: Swift Test
      run: swift test --enable-code-coverage --parallel --filter WrkstrmMainTests
